export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-surface": "#0b361d",
        "tertiary-container": "#ff9473",
        "surface-container-high": "#b5f0c2",
        "on-error-container": "#520c00",
        "on-primary-fixed": "#004b2d",
        "primary-fixed": "#7bfeb8",
        "surface-tint": "#006941",
        "primary-container": "#7bfeb8",
        "inverse-surface": "#001205",
        background: "#ddffe2",
        "on-tertiary-container": "#5f1600",
        "error-dim": "#b92902",
        "surface-variant": "#acecbb",
        "tertiary-fixed": "#ff9473",
        "on-secondary": "#ecf3ff",
        "inverse-on-surface": "#7ca785",
        "on-background": "#0b361d",
        secondary: "#005f99",
        "on-secondary-container": "#004a79",
        "inverse-primary": "#7bfeb8",
        "primary-fixed-dim": "#6cefab",
        "surface-container-highest": "#acecbb",
        "outline-variant": "#8bb795",
        "on-primary-fixed-variant": "#006b43",
        "tertiary-dim": "#952800",
        tertiary: "#a83206",
        "on-error": "#ffefec",
        surface: "#ddffe2",
        "on-tertiary-fixed-variant": "#6e1c00",
        "secondary-container": "#afd5ff",
        "on-primary-container": "#00603b",
        "error-container": "#f95630",
        "surface-container-lowest": "#ffffff",
        outline: "#568061",
        "secondary-dim": "#005386",
        "on-surface-variant": "#3b6447",
        "surface-dim": "#a0e4b1",
        "on-primary": "#caffdc",
        "tertiary-fixed-dim": "#ff7d55",
        "on-tertiary-fixed": "#340800",
        "on-secondary-fixed": "#00375b",
        primary: "#006941",
        "surface-container-low": "#cafdd4",
        "surface-bright": "#ddffe2",
        "secondary-fixed": "#afd5ff",
        "secondary-fixed-dim": "#93c8ff",
        "surface-container": "#bef5c9",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
      boxShadow: {
        soft: "0 10px 40px -15px rgba(11,54,29,0.06)",
      },
    },
  },
  plugins: [],
};
